### PR TITLE
doc(README) fix typos, wordwrap, etc.

### PR DESCRIPTION
**Pull request by rasa**
I was inspired after reading this guide. I found several howto's, but didn't really understand things until reading your guide. Thank you for writing it!

### CODE REVIEW

**Comment by javasboy** [comment]
Both the Markdown format and the rendered format look better.

**Comment by rasa** [comment]
The diff may not show it, but line [384](https://github.com/pirate/wireguard-docs/pull/88/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L384) has the word pubic instead of public. That's what initially inspired me.

**Comment by pirate** [comment]
Can you undo the line wrapping and I'll review the other changes. There are many different devices with different screen sizes so it doesn't make sense to line wrap manually.

**Comment by rasa** [comment]
Replaced by #89

**Pull request closed without merging**
